services:
  hub-front-end:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${PORT}:80"
    restart: unless-stopped
    env_file: ./.env
    
networks:
  default:
    external: true
    name: easypanel
