export { MunicipioDashboardPage } from './dashboard-page'
export { MunicipioSolucoesPage } from './solucoes-page'
export { MunicipioAlunosPage } from './alunos-page'
export { MunicipioUsuariosPage } from './usuarios-page'
export { MunicipioEscolasPage } from './escolas-page'
export { MunicipioRegioesPage } from './regioes-page'
export { MunicipioGruposPage } from './grupos-page'
export { MunicipioTurmasPage } from './turmas-page'
